
                          <option value="BAHAGIAN FORENSIK AKAUN">BAHAGIAN FORENSIK AKAUN</option>
                          <option value="BAHAGIAN FORENSIK TEKNOLOGI">BAHAGIAN FORENSIK TEKNOLOGI</option>
                          <option value="BAHAGIAN KESELAMATAN">BAHAGIAN KESELAMATAN</option>
                          <option value="BAH. KECEMERLANGAN &amp; PROFESIONALISME">BAH. KECEMERLANGAN &amp; PROFESIONALISME</option>
                          <option value="BAH. PENGURUSAN REKOD &amp; TEKNOLOGI MAKLUMAT">BAH. PENGURUSAN REKOD &amp; TEKNOLOGI MAKLUMAT</option>
                          <option value="BAH. PEMERIKSAAN DAN PERUNDINGAN">BAH. PEMERIKSAAN DAN PERUNDINGAN</option>
                          <option value="BAH. PENDIDIKAN MASYARAKAT">BAH. PENDIDIKAN MASYARAKAT</option>
                          <option value="BAH. PERISIKAN">BAH. PERISIKAN</option>
                          <option value="BAH. PENYELIDIKAN DAN PERANCANGAN">BAH. PENYELIDIKAN DAN PERANCANGAN</option>
                          <option value="BAH. PERUNDANGAN DAN PENDAKWAAN">BAH. PERUNDANGAN DAN PENDAKWAAN</option>
                          <option value="BAH. PENCEGAHAN PENGGUBAHAN WANG HARAM (AMLA)">BAH. PENCEGAHAN PENGGUBAHAN WANG HARAM (AMLA)</option>
                          <option value="BAHAGIAN OPERASI KHAS">BAHAGIAN OPERASI KHAS</option>
                          <option value="BAHAGIAN SIASATAN">BAHAGIAN SIASATAN</option>
                          <option value="CAWANGAN LAPORAN SPRM">CAWANGAN LAPORAN SPRM</option>
                          <option value="CAWANGAN MACMA">CAWANGAN MACMA</option>
                          <option value="CAWANGAN PELUCUTHAKAN HARTA">CAWANGAN PELUCUTHAKAN HARTA</option>
                          <option value="CAWANGAN PERLINDUNGAN PEMBERI MAKLUMAT">CAWANGAN PERLINDUNGAN PEMBERI MAKLUMAT</option>
                          <option value="CAWANGAN PERISKAN KHAS">CAWANGAN PERISIKAN KHAS</option>
                          <option value="CAWANGAN SASARAN OPERASI (OTC)">CAWANGAN SASARAN OPERASI (OTC)</option>
                          <option value="CAWANGAN RESPON PERTAMA">CAWANGAN RESPON PERTAMA</option>
                          <option value="CAWANGAN SIASATAN A">CAWANGAN SIASATAN A</option>
                          <option value="CAWANGAN SIASATAN B">CAWANGAN SIASATAN B</option>
                          <option value="CAWANGAN SIASATAN C">CAWANGAN SIASATAN C</option>
                          <option value="CAWANGAN SIASATAN D">CAWANGAN SIASATAN D</option>
                          <option value="CAWANGAN SIASATAN E">CAWANGAN SIASATAN E</option>
                          <option value="CAWANGAN SIASATAN F">CAWANGAN SIASATAN F</option>
                          <option value="CAWANGAN SIASATAN G">CAWANGAN SIASATAN G</option>
                          <option value="CAWANGAN TINDAKAN KHAS">CAWANGAN TINDAKAN KHAS</option>
                          <option value="JAWATAN KUASA MENILAI MAKLUMAT">JAWATAN KUASA MENILAI MAKLUMAT</option>
                          <option value="PENTADBIRAN SIASATAN">PENTADBIRAN SIASATAN</option>
                          <option value="PUSAT PENGURUSAN MAKLUMAT">PUSAT PENGURUSAN MAKLUMAT</option>
                          <option value="UNIT TATATERTIB">UNIT TATATERTIB</option>
