<option value="Affin Bank Berhad"> Affin Bank Berhad   </option>
<option value="Alliance Bank Malaysia Berhad"> Alliance Bank Malaysia Berhad     </option>
<option value="AmBank (M) Berhad"> AmBank (M) Berhad   </option>
<option value="BNP Paribas Malaysia Berhad"> BNP Paribas Malaysia Berhad     </option>
<option value="Bangkok Bank Berhad"> Bangkok Bank Berhad     </option>
<option value="Bank of America Malaysia Berhad"> Bank of America Malaysia Berhad     </option>
<option value="Bank of China (Malaysia) Berhad"> Bank of China (Malaysia) Berhad     </option>
<option value="Bank of Tokyo-Mitsubishi UFJ (Malaysia) Berhad"> Bank of Tokyo-Mitsubishi UFJ (Malaysia) Berhad    </option>
<option value="CIMB Bank Berhad"> CIMB Bank Berhad    </option>
<option value=" Citibank Berhad"> Citibank Berhad    </option>
<option value=" Deutsche Bank (Malaysia) Berhad"> Deutsche Bank (Malaysia) Berhad    </option>
<option value=" HSBC Bank Malaysia Berhad"> HSBC Bank Malaysia Berhad    </option>
<option value=" Hong Leong Bank Berhad">  Hong Leong Bank Berhad     </option>
<option value=" India International Bank (Malaysia) Berhad">  India International Bank (Malaysia) Berhad   </option>
<option value=" Industrial and Commercial Bank of China (Malaysia) Berhad"> Industrial and Commercial Bank of China (Malaysia) Berhad    </option>
<option value=" J.P. Morgan Chase Bank Berhad"> J.P. Morgan Chase Bank Berhad    </option>
<option value=" Malayan Banking Berhad">  Malayan Banking Berhad     </option>
<option value=" Mizuho Bank (Malaysia) Berhad"> Mizuho Bank (Malaysia) Berhad    </option>
<option value=" National Bank of Abu Dhabi Malaysia Berhad">  National Bank of Abu Dhabi Malaysia Berhad   </option>
<option value=" OCBC Bank (Malaysia) Berhad"> OCBC Bank (Malaysia) Berhad    </option>
<option value=" Public Bank Berhad">  Public Bank Berhad     </option>
<option value=" RHB Bank Berhad"> RHB Bank Berhad    </option>
<option value=" Standard Chartered Bank Malaysia Berhad"> Standard Chartered Bank Malaysia Berhad    </option>
<option value=" Sumitomo Mitsui Banking Corporation Malaysia Berhad"> Sumitomo Mitsui Banking Corporation Malaysia Berhad    </option>
<option value=" The Bank of Nova Scotia Berhad">  The Bank of Nova Scotia Berhad     </option>
<option value=" The Royal Bank of Scotland Berhad"> The Royal Bank of Scotland Berhad  </option>
<option value=" United Overseas Bank (Malaysia) Bhd"> United Overseas Bank (Malaysia) Bhd    </option>
<option value="Affin Islamic Bank Berhad"> Affin Islamic Bank Berhad     </option>
<option value="Al Rajhi Banking & Investment Corporation (Malaysia) Berhad"> Al Rajhi Banking & Investment Corporation (Malaysia) Berhad     </option>
<option value="Alliance Islamic Bank Berhad"> lliance Islamic Bank Berhad    </option>
<option value="AmIslamic Bank Berhad"> AmIslamic Bank Berhad     </option>
<option value="Asian Finance Bank Berhad"> Asian Finance Bank Berhad     </option>
<option value="Bank Islam Malaysia Berhad"> Bank Islam Malaysia Berhad    </option>
<option value="Bank Muamalat Malaysia Berhad"> Bank Muamalat Malaysia Berhad     </option>
<option value="CIMB Islamic Bank Berhad"> CIMB Islamic Bank Berhad    </option>
<option value="HSBC Amanah Malaysia Berhad"> HSBC Amanah Malaysia Berhad     </option>
<option value=" Hong Leong Islamic Bank Berhad">  Hong Leong Islamic Bank Berhad   </option>
<option value=" Kuwait Finance House (Malaysia) Berhad">  Kuwait Finance House (Malaysia) Berhad     </option>
<option value=" Maybank Islamic Berhad">  Maybank Islamic Berhad     </option>
<option value=" OCBC Al-Amin Bank Berhad">  OCBC Al-Amin Bank Berhad     </option>
<option value=" Public Islamic Bank Berhad">  Public Islamic Bank Berhad   </option>
<option value=" RHB Islamic Bank Berhad"> RHB Islamic Bank Berhad    </option>
<option value=" Standard Chartered Saadiq Berhad">  Standard Chartered Saadiq Berhad     </option>
<option value="Affin Investment Bank Berhad"> Affin Investment Bank Berhad    </option>
<option value="Alliance Investment Bank Berhad"> Alliance Investment Bank Berhad     </option>
<option value="AmInvestment Bank Berhad"> AmInvestment Bank Berhad    </option>
<option value="CIMB Investment Bank Berhad"> CIMB Investment Bank Berhad     </option>
<option value="Hong Leong Investment Bank Berhad"> Hong Leong Investment Bank Berhad     </option>
<option value="HwangDBS Investment Bank Berhad"> HwangDBS Investment Bank Berhad   </option>
<option value="KAF Investment Bank Berhad"> AF Investment Bank Berhad    </option>
<option value="Kenanga Investment Bank Berhad"> Kenanga Investment Bank Berhad    </option>
<option value="MIDF Amanah Investment Bank Berhad"> MIDF Amanah Investment Bank Berhad    </option>
<option value=" MIMB Investment Bank Berhad"> MIMB Investment Bank Berhad    </option>
<option value=" Maybank Investment Bank Berhad">  Maybank Investment Bank Berhad     </option>
<option value=" Public Investment Bank Berhad"> Public Investment Bank Berhad    </option>
<option value=" RHB Investment Bank Berhad">  RHB Investment Bank Berhad   </option>
<option value="ERF Sdn. Bhd"> ERF Sdn. Bhd.   </option>
<option value="Pengurusan Danaharta Nasional Berhad (now managed under Prokhas Sdn. Bhd.)"> Pengurusan Danaharta Nasional Berhad (now managed under Prokhas Sdn. Bhd.)    </option>
<option value="Lain-lain"> Lain-lain </option>
<option value="Tidak Diketahui"> Tidak Diketahui </option>