									<option value="Confidential">Confidential</option>
                                	<option value="Internal">Internal</option>
                                	<option value="Public">Public</option>
                                	<option value="Suspended">Suspended</option>
                                	<option value="Alert">Alert</option>
                                	<option value="Yellow Notice">Yellow Notice</option>
                                	<option value="Blue Notice">Blue Notice</option>
                                	<option value="Red Notice">Red Notice</option>
                                	<option value="Others">Others</option>