                    <option value="Malaysian Chinese">Malaysian Chinese</option>
                    <option value="Malaysian Indians">Malaysian Indians</option>
                    <option value="Malaysians">Malaysians</option>
                    <option value="Malaysian Malay">Malaysian Malay</option>
                    <option value="Malaysian Siamese">Malaysian Siamese</option>
                    <option value="Bumiputera">Bumiputera</option>
                    <option value="Iban">Iban</option>
                    <option value="Orang Asli">Orang Asli</option>
                    <option value="Kadazan">Kadazan</option>
                    <option value="Kadazan-Dusun">Kadazan-Dusun</option>
                    <option value="Bidayuh">Bidayuh</option>
                    <option value="Dusun">Dusun</option>
                    <option value="Peranakan">Peranakan</option>
                    <option value="Orang Ulu">Orang Ulu</option>
                    <option value="Melanau">Melanau</option>
                    <option value="Bisaya (Borneo)">Bisaya (Borneo)</option>
                    <option value="Senoi">Senoi</option>
                    <option value="Negritos">Negritos</option>
                    <option value="Kenyah">Kenyah</option>
                    <option value="Semang">Semang</option>
                    <option value="Kwijau">Kwijau</option>
                    <option value="Ida'an">Ida'an</option>
                    <option value="Lotud">Lotud</option>
                    <option value="Dumpas">Dumpas</option>
                    <option value="Tidong">Tidong</option>
                    <option value="Others">Others</option>
                    <option value="Unknown">Unknown</option>