                                   <option value="Sex Exploitation">Sex Exploitation</option>
                                   <option value="Labour Exploitation">Labour Exploitation</option>
                                   <option value="Maid Exploitation">Maid Exploitation</option>
                                   <option value="Baby and Child Exploitation">Baby and Child Exploitation</option>
                                   <option value="Beggar Exploitation">Beggar Exploitation</option>
                                   <option value="Smuggling(Air)">Smuggling(Air)</option>
                                   <option value="Smuggling(Land)">Smuggling(Land)</option>
                                   <option value="Smuggling(Sea)">Smuggling(Sea)</option>
                                   <option value="Organt Smuggling">Organt Smuggling</option>
                                   <option value="Malaysian Passport(Fake)">Malaysian Passport(Fake)</option>
                                   <option value="Malaysian Passport(Genuine)">Malaysian Passport(Genuine)</option>
                                   <option value="Immigration Sticker(Fake)">Immigration Sticker(Fake)</option>
                                   <option value="Immigration Sticker(Genuine)">Immigration Sticker(Genuine)</option>
                                   <option value="Endosment(Fake)">Endosment(Fake)</option>
                                   <option value="Endosment(Genuine)">Endosment(Genuine)</option>
                                   <option value="Document(Fake)">Document(Fake)</option>
                                   <option value="Terrorisme">Terrorisme</option>
                                   <option value="ATM Scam">ATM Scam</option>
                                   <option value="Money Scam">Money Scam</option>
                                   <option value="Drug Smuggling">Drug Smuggling</option>
                                   <option value="Commersial Crime">Commersial Crime</option>
                                   <option value="Visa(Genuine)">Visa(Genuine)</option>
                                   <option value="Visa(Fake)">Visa(Fake)</option>
                                   <option value="International Passport(Genuine)">International Passport(Genuine)</option>
                                   <option value="International Passport(Fake)">International Passport(Fake)</option>
                                   <option value="ID/Driving License(Genuine)">ID/Driving License(Genuine)</option>
                                   <option value="ID/Driving License(Fake)">ID/Driving License(Fake)</option>
                                   <option value="Immigration Support Document(Genuine)">Immigration Support Document(Genuine)</option>
                                   <option value="Immigration Support Document(Fake)">Immigration Support Document(Fake)</option>
                                   <option value="U-Turn South">U-Turn South</option>
                                   <option value="U-Turn East">U-Turn East</option>
                                   <option value="U-Turn North">U-Turn North</option>
                                   <option value="U-Turn West">U-Turn West</option>
                                   <option value="Fraud Document">Fraud Document</option>
                                   <option value="Lost Document">Lost Document</option>
                                   <option value="Stealing Document">Stealing Document</option>
                                   <option value="Using Other Document">Using Other Document</option>
                                   <option value="Impostor">Impostor</option>
                                   <option value="Urghur Etnic">Urghur Etnic</option>
                                   <option value="Rohingya Etnic">Rohingya Etnic</option>
                                   <option value="Foreign Placement">Foreign Placement</option>
                                   <option value="Political">Political</option>
                                   <option value="Others">Others</option>
                                   <option value="Unknown">Unknown</option>