								<option value="Amber">Amber</option>
                                <option value="Black">Black</option>
                                <option value="Brown">Brown</option>
                                <option value="Gray">Gray</option>
                                <option value="Green">Green</option>
                                <option value="Hazel">Hazel</option>
                                <option value="Red and Violet">Red and Violet</option>
                                <option value="Others">Others</option>
								<option value="Unknown">Unknown</option>