<!--/**
 * @author Kamaruzzaman
 * @copyright 2017
 */-->
 <style type="text/css">
	table.tableizer-table {
		font-size: 12px;
		border: 1px solid #CCC; 
		font-family: Arial, Helvetica, sans-serif;
	} 
	.tableizer-table td {
		padding: 4px;
		margin: 3px;
		border: 1px solid #CCC;
	}
	.tableizer-table th {
		background-color: #104E8B; 
		color: #FFF;
		font-weight: bold;
	}
</style>
<table class="tableizer-table">
<thead><tr class="tableizer-firstrow"><th>Bil.</th><th>TAJUK TENDER</th><th>NOMBOR TENDER</th><th>KATEGORI PEROLEHAN</th><th>KEMENTERIAN</th><th>AGENSI</th><th>NAMA SYARIKAT</th><th>NO DAFTAR SYARIKAT</th><th>NO MOF/PKK</th><th>PETENDER BERJAYA</th><th>HARGA SETUJU TERIMA (RM)</th></tr></thead><tbody>
 <tr><td>1</td><td>MEMBEKAL RANGSUM PUKAL MINUMAN (KORDIALBUAH/ BERPERISA) UNTUK ANGKATAN TENTERA MALAYSIA (ATM) BAGI KAWASAN I DAN II SEMENANJUNG (PERLIS, KEDAH, PULAU PINANG DAN PERAK) BAGI TEMPOH TIGA (3) TAHUN</td><td>QT190000000035753</td><td>Bekalan</td><td>KEMENTERIAN PERTAHANAN</td><td>BAHAGIAN PEROLEHAN</td><td>FRESHIE (M) SDN. BHD</td><td>88337-M</td><td>&nbsp;</td><td>FRESHIE (M) SDN. BHD. NO. DAFTAR SYARIKAT: 88337-MNO. DAFTAR MOF/PKK:</td><td>1816231.2</td></tr>
 <tr><td>2</td><td>MEMBEKAL RANGSUM PUKAL MINUMAN (KORDIAL/ BUAH/ BERPERISA) UNTUK ANGKATAN TENTERA MALAYSIA (ATM) BAGI KAWASAN V, VII DAN VIII SEMENANJUNG (JOHOR, PAHANG, KELANTAN DAN TERENGGANU) BAGI TEMPOH TIGA (3) TAHUN</td><td>QT190000000033623</td><td>Bekalan</td><td>KEMENTERIAN PERTAHANAN</td><td>BAHAGIAN PEROLEHAN</td><td>FRESHIE (M) SDN. BHD</td><td>88337-M</td><td>&nbsp;</td><td>FRESHIE (M) SDN. BHD.NO. DAFTAR SYARIKAT: 88337-MNO. DAFTAR MOF/PKK:</td><td>1305710</td></tr>
 <tr><td>3</td><td>MEMBEKAL RANGSUM PUKAL MINUMAN (KORDIAL/ BUAH/ BERPERISA) UNTUK ANGKATAN TENTERA MALAYSIA (ATM) BAGI KAWASAN III DAN IV SEMENANJUNG (WILAYAH PERSEKUTUAN KUALA LUMPUR, SELANGOR, MELAKA DAN NEGERI SEMBILAN ) BAGI TEMPOH TIGA (3) TAHUN</td><td>QT190000000040832</td><td>Bekalan</td><td>KEMENTERIAN PERTAHANAN</td><td>BAHAGIAN PEROLEHAN</td><td>FRESHIE (M) SDN. BHD</td><td>88337-M</td><td>&nbsp;</td><td>FRESHIE (M) SDN. BHD.NO.  DAFTAR SYARIKAT: 88337-MNO. DAFTAR MOF/PKK:</td><td>1735480.2</td></tr>
 <tr><td>4</td><td>TENDER PERKHIDMATAN PENGAWAL KESELAMATAN TANPA SENJATA API DI AKADEMI KEPIMPINAN PENDIDIKAN TINGGI (AKEPT) KEMENTERIAN PENDIDIKAN MALAYSIA TAHUN 2019</td><td>QT190000000049663</td><td>Perkhidmatan Bukan Perunding</td><td>KEMENTERIAN PENDIDIKAN MALAYSIA</td><td>AKADEMI KEPIMPINAN PENDIDIKAN TINGGI (AKEPT)</td><td>SWACK SECURITY SERVICES SDN BHD</td><td>184439-X</td><td>&nbsp;</td><td>SWACK SECURITY SERVICES SDN BHD NO. DAFTAR SYARIKAT: 184439-XNO. DAFTAR MOF/PKK:</td><td>997212.38</td></tr>
 <tr><td>5</td><td>PELANJUTAN TEMPOH KONTRAK DAN PERTAMBAHAN KOS BAGI e-BIDDING MEMBEKAL, MEMASANG, MENGUJITERIMA, MENTAULIAH DAN MENGKONGFIGURASI KOMPUTER, MESIN PENCETAK, MS OFFICE DAN ANTIVIRUS UNTUK TUJUAN SEWAAN DI IBU PEJABAT KPKK DAN CAWANGAN NEGERI</td><td>QT18000000000000</td><td>Perkhidmatan Bukan Perunding</td><td>JABATAN PERDANA MENTERI</td><td>PEJABAT KETUA PEGAWAI KESELAMATAN KERAJAAN MALAYSIA</td><td>ALGOMINDA SDN. BHD</td><td>670774-A</td><td>&nbsp;</td><td>ALGOMINDA SDN. BHD. NO. DAFTAR SYARIKAT: 670774-ANO. DAFTAR MOF/PKK:</td><td>57900</td></tr>
 <tr><td>6</td><td>PERKHIDMATAN MENYEDIAKAN DAN MEMBEKALKAN MAKANAN BERMASAK SERTA MINUMAN KEPADA PELAJAR-PELAJAR DI INSTITUT KEMAHIRAN BELIA NEGARA (IKBN) PERETAK, SELANGOR</td><td>QT190000000044806</td><td>Perkhidmatan Bukan Perunding</td><td>KEMENTERIAN BELIA DAN SUKAN</td><td>KEMENTERIAN BELIA DAN SUKAN</td><td>DENGIR ENTERPRISE</td><td>SA0145725-T</td><td>&nbsp;</td><td>DENGIR ENTERPRISE NO. DAFTAR SYARIKAT: SA0145725-TNO. DAFTAR MOF/PKK:</td><td>6269580</td></tr>
 <tr><td>7</td><td>PERKHIDMATAN KAWALAN KESELAMATAN TANPA SENJATA DI INSTITUT KEMAHIRAN TINGGI BELIA NEGARA (IKTBN) BACHOK, KELANTAN</td><td>QT190000000045762</td><td>Perkhidmatan Bukan Perunding</td><td>KEMENTERIAN BELIA DAN SUKAN</td><td>KEMENTERIAN BELIA DAN SUKAN</td><td>SHELTER SECURITY SERVICES SDN. BHD</td><td>636512-D</td><td>&nbsp;</td><td>SHELTER SECURITY SERVICES SDN. BHD.NO. DAFTAR SYARIKAT: 636512-DNO. DAFTAR MOF/PKK:</td><td>1182967.63</td></tr>
 <tr><td>8</td><td>PERKHIDMATAN KAWALAN KESELAMATAN TANPA SENJATA DI INSTITUT KEMAHIRAN BELIA NEGARA (IKBN) TANAH MERAH, KELANTAN</td><td>QT190000000045770</td><td>Perkhidmatan Bukan Perunding</td><td>KEMENTERIAN BELIA DAN SUKAN</td><td>KEMENTERIAN BELIA DAN SUKAN</td><td>RAHMAT BERNAS SECURITY SERVICES SDN. BHD</td><td>354421-D</td><td>&nbsp;</td><td>RAHMAT BERNAS SECURITY SERVICES SDN. BHD. NO. DAFTAR SYARIKAT: 354421-DNO. DAFTAR MOF/PKK:</td><td>1187157.6</td></tr>
 <tr><td>9</td><td>PERKHIDMATAN MENYEDIAKAN DAN MEMBEKALKAN MAKANAN BERMASAK SERTA MINUMAN KEPADA PELAJAR-PELAJAR DI INSTITUT KEMAHIRAN TINGGI BELIA NEGARA (IKTBN) BACHOK, KELANTAN</td><td>QT190000000044764</td><td>Perkhidmatan Bukan Perunding</td><td>KEMENTERIAN BELIA DAN SUKAN</td><td>KEMENTERIAN BELIA DAN SUKAN</td><td>BNR SETIA ENTERPRISE</td><td>KT0229813-K</td><td>&nbsp;</td><td>BNR SETIA ENTERPRISE NO. DAFTAR SYARIKAT: KT0229813-KNO. DAFTAR MOF/PKK:</td><td>6634116</td></tr>
 <tr><td>10</td><td>PERKHIDMATAN MENYEDIAKAN DAN MEMBEKALKAN MAKANAN BERMASAK SERTA MINUMAN KEPADA PELAJAR-PELAJAR DI INSTITUT KEMAHIRAN BELIA NEGARA (IKBN) KUALA LANGAT, SELANGOR</td><td>QT190000000044190</td><td>Perkhidmatan Bukan Perunding</td><td>KEMENTERIAN BELIA DAN SUKAN</td><td>KEMENTERIAN BELIA DAN SUKAN</td><td>NAKAR RESOURCES</td><td>1803271-V</td><td>&nbsp;</td><td>NAKAR RESOURCES NO. DAFTAR SYARIKAT: 1803271-VNO. DAFTAR MOF/PKK:</td><td>4643881.2</td></tr>
</tbody></table>
      </section>
        <!-- footer content -->
        <?php include 'footer.php'; ?>
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <?php include 'include/js.php'; ?>
  </body>
</html>